baseURL = "https://marcoagarcia.com"
languageCode = "en-us"
title = "Marco A. Garcia"
copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
theme = "npq-hugo"
pygmentsUseClasses=true

[params]
  author = "Marco A. Garcia"
  description = "This is my resume website"
  keywords = "hugo resume"
  useAvatar = true
  microBlogSection = "posts"
  displayMicroBlog = false
  displayRecent = false 
  displayHomeContent = false
  recentMax = 4
  mail = "m4garci4@gmail.com"
  phone = "Please refer to paper resume"
  formspreeID = "yourformspreeID"

[menu]
  [[menu.main]]
    name = "home"
    pre = "<i class=\"fas fa-home fa-sm\"></i>"
    url = "/"
    weight = -9 
  [[menu.main]]
    name = "blog"
    pre = "<i class=\"fas fa-keyboard fa-ms\"></i>"
    url = "/blog/"
    weight = -8
  [[menu.main]]
    name = "tags"
    pre = "<i class=\"fas fa-tags fa-ms\"></i>"
    url = "/tags"
    weight = -7 
  [[menu.main]]
    name = "github"
    pre = "<i class=\"fab fa-github fa-ms\"></i>"
    url = "https://github.com/magarcia-22"
    weight = -6 
  [[menu.main]]
    name = "contact"
    pre = "<i class=\"far fa-envelope\"></i>"
    url = "/contact"
    weight = -1 
